name: backend
version: "0.1.0.0"
category: "web"
author: "Yuriy Lazarev"
maintainer: unisay@users.noreply.github.com
copyright: "Yuriy Lazarev"
github: "unisay/backend"
extra-source-files:
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wimplicit-prelude
- -Wtabs
- -Wmissing-local-signatures
- -fhelpful-errors

default-extensions:
- ApplicativeDo
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- EmptyCase
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators

dependencies:
- base
- protolude

_common-deps: &common-deps
- aeson
- ekg
- envy
- exceptions
- lens
- mtl
- monad-logger
- network-uri
- protolude
- servant
- servant-server
- text
- time
- transformers
- unordered-containers
- wai
- warp

library:
  source-dirs: src
  exposed-modules:
  - Main
  dependencies: *common-deps

internal-libraries:
  backend-internal:
    source-dirs: src
    exposed-modules:
    - Preamble
    dependencies: *common-deps

executables:
  backend:
    main: App
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  spec:
    main: Main
    source-dirs:
    - test
    dependencies:
    - backend-internal
    - hedgehog
    ghc-options:
    - -threaded
